# Generated by Django 5.0.6 on 2024-06-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
