# Generated by Django 5.0.6 on 2024-06-02 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_user_registration_date_alter_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateField(default=datetime.date(2024, 6, 2)),
        ),
    ]
