# Generated by Django 5.0.6 on 2024-06-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsession',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
