# Generated by Django 5.0.6 on 2024-06-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userpoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_pois',
            field=models.ManyToManyField(through='main.UserPOI', to='main.poi'),
        ),
    ]
